/// Flutter icons StatusIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StatusIcon
///      fonts:
///       - asset: fonts/StatusIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class StatusIcon {
  StatusIcon._();

  static const _kFontFam = 'StatusIcon';

  static const IconData decision_making = IconData(0xe800, fontFamily: _kFontFam);
}
